global:
  clusterConfiguration:
    cloud:
      prefix: prefix
    clusterType: "Cloud"
  enabledModules:
    __ConstantChoices__:
      - ["vertical-pod-autoscaler-crd"]
      - ["priority-class"]
  modulesImages:
    registry: registry.deckhouse.io
    registryDockercfg: cfg
    tags:
      common:
        csiExternalProvisioner116: imagehash
        csiExternalAttacher116: imagehash
        csiExternalProvisioner119: imagehash
        csiExternalAttacher119: imagehash
        csiExternalResizer: imagehash
        csiNodeDriverRegistrar: imagehash
      cloudProviderAzure:
        csiNodeDriverRegistrar: imagehash
        simpleBridge: imagehash
        cloudControllerManager: imagehash
        pdCsiPlugin: imagehash
        livenessprobe: imagehash
        azurediskCsi: imagehash
  discovery:
    d8SpecificNodeCountByRole:
      worker: 1
      master:
        __ConstantChoices__: ["1", "3"]
    podSubnet: 10.0.1.0/16
    kubernetesVersion: 1.19.0
  modules:
    placement:
      __ConstantChoices__:
      - {}
      - customTolerationKeys:
          - "test-1"
          - "test-2/master"

cloudProviderAzure:
  internal:
    providerClusterConfiguration:
      provider:
        clientId: zzz
        clientSecret: zzz
        subscriptionId: zzz
        tenantId: zzz
        location: zzz
    providerDiscoveryData:
      resourceGroupName: zzz
      vnetName: zzz
      subnetName: zzz
      instances:
        urn: zzz
        diskType: zzz
    storageClasses:
    - name: aaa
      type: AAA
    - name: bbb
      type: BBB
    - name: ccc
      type: CCC
