{{- define "vsphere_cloud_config" }}
global:
  user: {{ .Values.cloudProviderVsphere.internal.username | required ".Values.cloudProviderVsphere.internal.username is required" | quote }}
  password: {{ .Values.cloudProviderVsphere.internal.password | required ".Values.cloudProviderVsphere.internal.password is required" | quote }}
  insecureFlag: {{ .Values.cloudProviderVsphere.internal.insecure }}

vcenter:
  main:
    server: {{ .Values.cloudProviderVsphere.internal.server | required ".Values.cloudProviderVsphere.internal.server is required" | quote }}
    datacenters:
      - {{ .Values.cloudProviderVsphere.internal.datacenter | required ".Values.cloudProviderVsphere.internal.datacenter is required" | quote }}
{{- if not (semverCompare "=1.22" .Values.global.discovery.kubernetesVersion) }}
  {{- if not (empty .Values.cloudProviderVsphere.internal.externalNetworkNames) }}
    externalNetworkNames:
    {{- .Values.cloudProviderVsphere.internal.externalNetworkNames | toYaml | nindent 6 }}
  {{- end }}
  {{- if not (empty .Values.cloudProviderVsphere.internal.internalNetworkNames) }}
    internalNetworkNames:
    {{- .Values.cloudProviderVsphere.internal.internalNetworkNames | toYaml | nindent 6 }}
  {{- end }}
    vmFolderPath: {{ .Values.cloudProviderVsphere.internal.vmFolderPath | required ".Values.cloudProviderVsphere.internal.vmFolderPath is required" }}
{{- else }}

nodes:
  {{- if not (empty .Values.cloudProviderVsphere.internal.externalNetworkNames) }}
  externalVmNetworkName: {{ join "," .Values.cloudProviderVsphere.internal.externalNetworkNames }}
  {{- end }}
  {{- if not (empty .Values.cloudProviderVsphere.internal.internalNetworkNames) }}
  internalVmNetworkName: {{ join "," .Values.cloudProviderVsphere.internal.internalNetworkNames }}
  {{- end }}
{{- end }}

labels:
  region: {{ .Values.cloudProviderVsphere.internal.regionTagCategory | required ".Values.cloudProviderVsphere.internal.regionTagCategory is required" | quote }}
  zone: {{ .Values.cloudProviderVsphere.internal.zoneTagCategory | required ".Values.cloudProviderVsphere.internal.zoneTagCategory is required" | quote }}

{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-controller-manager
  namespace: d8-cloud-provider-vsphere
{{ include "helm_lib_module_labels" (list . (dict "app" "cloud-controller-manager")) | indent 2 }}
type: Opaque
data:
  cloud-config: {{ include "vsphere_cloud_config" . | b64enc | quote }}
