global:
  enabledModules: ["vertical-pod-autoscaler-crd", "priority-class"]
  modulesImages:
    registry: registry.deckhouse.io
    registryDockercfg: cfg
    tags:
      common:
        csiExternalProvisioner116: imagehash
        csiExternalAttacher116: imagehash
        csiExternalProvisioner119: imagehash
        csiExternalAttacher119: imagehash
        csiExternalResizer: imagehash
        csiNodeDriverRegistrar: imagehash
      cloudProviderAws:
        ebsCsiPlugin: imagehash
        simpleBridge: imagehash
        cloudControllerManager116: imagehash
        cloudControllerManager119: imagehash
        nodeTerminationHandler: imagehash
  discovery:
    d8SpecificNodeCountByRole:
      master:
        __ConstantChoices__: ["1", "3"]
      worker: 1
    podSubnet: 10.0.1.0/16
    kubernetesVersion:
      __ConstantChoices__: [1.19.10, 1.20.8, 1.21.10]
  modules:
    placement:
      __ConstantChoices__:
      - {}
      - customTolerationKeys:
          - "test-1"
          - "test-2/master"

cloudProviderAws:
  internal:
    zoneToSubnetIdMap:
      zonea: aaa
      zoneb: bbb
    providerAccessKeyId: myprovacckeyid
    providerSecretAccessKey: myprovsecretaccesskey
    zones: ["zonea", "zoneb"]
    region: myregion
    instances:
      iamProfileName: myiamprofile
      additionalSecurityGroups:
        __ConstantChoices__:
        - __EmptyItem__
        - ["id1", "id2"]
    loadBalancerSecurityGroup: mylbsecgroupid
    keyName: mykeyname
    tags:
      aaa: aaa
