kind: ClusterConfiguration
apiVersions:
- apiVersion: deckhouse.io/v1
  openAPISpec:
    type: object
    additionalProperties: false
    required: [apiVersion, kind, clusterType, kubernetesVersion, podSubnetCIDR, serviceSubnetCIDR, clusterDomain]
    properties:
      apiVersion:
        type: string
        enum: [deckhouse.io/v1, deckhouse.io/v1alpha1]
      kind:
        type: string
        enum: [ClusterConfiguration]
      clusterType:
        type: string
        enum: [Cloud, Static]
      cloud:
        type: object
        required: [provider]
        additionalProperties: false
        properties:
          provider:
            type: string
            enum:
            - "OpenStack"
            - "AWS"
            - "GCP"
            - "Yandex"
            - "vSphere"
            - "Azure"
          prefix:
            type: string
            pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
      podSubnetCIDR:
        type: string
      podSubnetNodeCIDRPrefix:
        type: string
        default: "24"
      serviceSubnetCIDR:
        type: string
      clusterDomain:
        type: string
        default: "cluster.local"
      defaultCRI:
        type: string
        enum:
        - "Docker"
        - "Containerd"
        - "NotManaged"
        default: "Containerd"
      kubernetesVersion:
        type: string
        enum:
        - "1.19"
        - "1.20"
        - "1.21"
        - "1.22"
      packagesProxy:
        type: object
        additionalProperties: false
        properties:
          uri:
            type: string
          username:
            type: string
          password:
            type: string
        oneOf:
          - properties:
              uri:
                type: string
            additionalProperties: false
            required: [uri]
          - properties:
              uri:
                type: string
              username:
                type: string
              password:
                type: string
            additionalProperties: false
            required: [uri, username, password]
    oneOf:
    - properties:
        clusterType:
           enum: [Static]
    - properties:
        clusterType:
           enum: [Cloud]
      cloud: {}
      required: [cloud]
