global:
  enabledModules: ["vertical-pod-autoscaler-crd"]
  modulesImages:
    registry: registry.deckhouse.io
    registryDockercfg: cfg
    tags:
      common:
        csiExternalProvisioner116: imagehash
        csiExternalAttacher116: imagehash
        csiExternalProvisioner119: imagehash
        csiExternalAttacher119: imagehash
        csiExternalResizer: imagehash
        csiNodeDriverRegistrar: imagehash
      cloudProviderVsphere:
        vsphereCsi: imagehash
        cloudControllerManager116: imagehash
        cloudControllerManager119: imagehash
  discovery:
    d8SpecificNodeCountByRole:
      worker: 1
      master:
        __ConstantChoices__: ["1", "3"]
    podSubnet: 10.0.1.0/16
    kubernetesVersion:
      __ConstantChoices__: [1.19.10, 1.20.8, 1.21.10]
  modules:
    placement:
      __ConstantChoices__:
      - {}
      - customTolerationKeys:
          - "test-1"
          - "test-2/master"

cloudProviderVsphere:
  __ConstantChoices__:
  - internal: # maximum
      datacenter: test
      datastores:
      - name: mydsname
        path: /my/ds/path/mydsname
        zones: ["zonea", "zoneb"]
      server: myhost
      username: myuname
      password: myPaSsWd
      insecure:
        __ConstantChoices__:
        - true
        - false
      regionTagCategory: myregtagcat
      zoneTagCategory: myzonetagcat
      region: myreg
      sshKey: mysshkey1
      masterInstanceClass:
        datastore: dev/lun_1
        mainNetwork: k8s-msk/test_187
        memory: 8192
        numCPUs: 4
        template: dev/golden_image
      vmFolderPath: dev/test
      zones: ["aaa", "bbb"]
      compatibilityFlag: ""
