---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet
  namespace: d8-monitoring
{{ include "helm_lib_module_labels" (list . (dict "prometheus" "main")) | indent 2 }}
spec:
  jobLabel: k8s-app
  endpoints:
  - port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
      cert:
        secret:
          name: prometheus-scraper-tls
          key: tls.crt
      keySecret:
        name: prometheus-scraper-tls
        key: tls.key
    honorLabels: true
    relabelings:
    - regex: endpoint|namespace|pod|service
      action: labeldrop
    - sourceLabels: [__meta_kubernetes_endpoint_address_target_name]
      targetLabel: node
    - targetLabel: scrape_endpoint
      replacement: kubelet
    - targetLabel: tier
      replacement: cluster
  - port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
      cert:
        secret:
          name: prometheus-scraper-tls
          key: tls.crt
      keySecret:
        name: prometheus-scraper-tls
        key: tls.key
    path: /metrics/cadvisor
    honorLabels: true
    relabelings:
    - regex: endpoint|namespace|pod|service
      action: labeldrop
    - sourceLabels: [__meta_kubernetes_endpoint_address_target_name]
      targetLabel: node
    - targetLabel: scrape_endpoint
      replacement: cadvisor
    - targetLabel: tier
      replacement: cluster
    metricRelabelings:
    - sourceLabels: [namespace]
      regex: '^$'
      action: drop
    - sourceLabels: [pod]
      regex: '^$'
      action: drop
    - sourceLabels: [container]
      regex: '^$'
      action: drop
    - sourceLabels: [pod_name]
      regex: '^$'
      action: drop
    - sourceLabels: [container_name]
      separator: ""
      regex: '^$'
      action: drop
    - sourceLabels: [container_name]
      targetLabel: container
    - sourceLabels: [pod_name]
      targetLabel: pod
    {{- end }}
    - regex: container_name|pod_name|id|image|name
      action: labeldrop
  - port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
      cert:
        secret:
          name: prometheus-scraper-tls
          key: tls.crt
      keySecret:
        name: prometheus-scraper-tls
        key: tls.key
    path: /metrics/probes
    honorLabels: true
    relabelings:
      - regex: endpoint|namespace|pod|service
        action: labeldrop
      - sourceLabels: [__meta_kubernetes_endpoint_address_target_name]
        targetLabel: node
      - targetLabel: scrape_endpoint
        replacement: probes
      - targetLabel: tier
        replacement: cluster
  selector:
    matchLabels:
      k8s-app: kubelet
  namespaceSelector:
    matchNames:
    - d8-monitoring
